services:
  demo-cicd:
    image: pelado1998/demo-cicd:latest
    container_name: api-http
    build:
      context: "./api/"
      dockerfile: "Dockerfile"
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=http